export const ROUTE_PATH = {
  DEFAULT: '/',
  LOGIN: '/login',
  EQUIPMENTS_ADMIN: '/equipments-admin',
  EQUIPMENTS_USER: '/equipment-user',
  MY_EQUIPMENTS: '/my-equipments',
};

export const STORE = {
  RESPONSE: 'STORE_RESPONSE',
  ERRORS: 'STORE_ERRORS',
  SUCCESSFUL_APIS: 'STORE_SUCCESSFUL_APIS',
  MODAL: 'STORE_MODAL',
  LOADING: {
    INCREASE: 'INCREASE_LOADING',
    DECREASE: 'DECREASE_LOADING',
    RESET: 'RESET_LOADING',
  },
};

export const RESET = {
  RESPONSE: 'RESET_RESPONSE'
};

export const HTTP_METHOD = {
  POST: 'POST',
  GET: 'GET',
  PUT: 'PUT',
  DELETE: 'DELETE',
};

export const STATUS_CODE = {
  Success: 200,
  Unauthorized: 401,
  NoContent: 204,
  BadRequest: 400,
};

export const SERVICE_NAME = {
  LOGIN: 'login',
  GET_ALL_EQUIPMENTS: 'getAllEquipments',
  CREATE_A_EQUIPMENT: 'createAEquipment',
  EDIT_A_EQUIPMENT: 'editAEquipment',
  DELETE_A_EQUIPMENT: 'deleteAEquipment',
  EDIT_STATUS_EQUIPMENT: 'editStatusEquipment',
  MY_EQUIPMENTS: 'myEquipments',
  BOOK_A_EQUIPMENT: 'bookAEquipment',
  RETURN_A_EQUIPMENT: 'returnAEquipment'
};

export const CONFIG = {
  [SERVICE_NAME.LOGIN]: process.env.REACT_APP_API_LOGIN,
  [SERVICE_NAME.GET_ALL_EQUIPMENTS]: process.env.REACT_APP_API_GET_ALL_EQUIPMENTS,
  [SERVICE_NAME.CREATE_A_EQUIPMENT]: process.env.REACT_APP_API_CREATE_A_EQUIPMENT,
  [SERVICE_NAME.EDIT_A_EQUIPMENT]: process.env.REACT_APP_API_UPDATE_A_EQUIPMENT,
  [SERVICE_NAME.DELETE_A_EQUIPMENT]: process.env.REACT_APP_API_DELETE_A_EQUIPMENT,
  [SERVICE_NAME.EDIT_STATUS_EQUIPMENT]: process.env.REACT_APP_API_UPDATE_STATUS_EQUIPMENT,
  [SERVICE_NAME.MY_EQUIPMENTS]: process.env.REACT_APP_API_MY_EQUIPMENTS,
  [SERVICE_NAME.BOOK_A_EQUIPMENT]: process.env.REACT_APP_API_BOOK_A_EQUIPMENT,
  [SERVICE_NAME.RETURN_A_EQUIPMENT]: process.env.REACT_APP_API_RETURN_A_EQUIPMENT,
};

export const MODAL_TYPE = {
  CONFIRM_MODAL: 'CONFIRM_MODAL',
  RESULT_MODAL: 'RESULT_MODAL',
  CREATE_EDIT_EQUIPMENT_MODAL: 'CREATE_EDIT_EQUIPMENT_MODAL'
};

export const EQUIPMENT_STATUS = {
  AVAILABLE: 1,
  WAITING_FOR_APPROVAL: 2,
  NOT_AVAILABLE: 3
}